/* 
 * SPDX-License-Identifier: MIT OR Apache-2.0
 *
 * Copyright (c) 2023 SUSE LLC
 *
 * Author: Roy Hopkins <rhopkins@suse.de>
 */


#ifndef KBSCLIENT_H
#define KBSCLIENT_H

/* Generated with cbindgen:0.26.0 */

/* This file is generated using cbindgen. Do not edit this file directly. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

uintptr_t get_svsm_secret(const uint8_t *url,
                          uintptr_t url_len,
                          const uint8_t *path,
                          uintptr_t path_len,
                          const uint8_t *evidence,
                          uintptr_t evidence_len,
                          const uint8_t *tee_key,
                          uintptr_t tee_key_len,
                          const uint8_t *certs,
                          uintptr_t certs_len,
                          uint8_t *resource_buf,
                          uintptr_t resource_buf_len);

#endif /* KBSCLIENT_H */
